build:
  stage: build
  image: node:20.11.1-alpine3.19
  services:
    - node:20.11.1-alpine3.19:dind
  before_script:
    - apk add openssh-client git
    - eval $(ssh-agent -s)
    - echo "${SSH_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - npm ci 
    - npm run build
