stages:
  - build
  - deploy
  

build_test:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add openssh-client git
    - eval $(ssh-agent -s)
    - echo "${SSH_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - npm ci 
    - npm run build

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.zaryad.tech
    - export DOCKER_HOST=tcp://127.0.0.1:2375 && docker build -t registry.zaryad.tech/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME .
    - docker push registry.zaryad.tech/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME
 
