stages:
  - build
  - deploy

# Определение стадии билда
build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.aic.ru
    - docker build -f Dockerfile -t registry.aic.ru/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME .
    - docker push registry.aic.ru/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME


# Определение стадии деплоя
deploy:
  stage: deploy
  image: debian:11
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.aic.ru
    - docker pull registry.aic.ru/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME
    - if docker ps -a| grep "$CI_PROJECT_NAME"; then docker stop $CI_PROJECT_NAME && docker container rm $CI_PROJECT_NAME ; fi
    - docker run -p 127.0.0.1:3000:3000 --restart always --name $CI_PROJECT_NAME -d registry.aic.ru/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME
    - docker container  prune -f
    - docker image prune -f
  only:
    - main
