import type { Metadata } from 'next';
import './globals.css';
import { Header } from '../widgets/header';

export const metadata: Metadata = {
	title: 'Next Layout',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
