import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Private Layout',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="ru">
			{/*<body className={inter.className}>{children}</body>*/}
			<body className="sdsdssdsd">{children}</body>
		</html>
	);
}
